# Generated by Django 4.2 on 2023-04-05 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_job_departament_delete_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 3, 59, 18, 167520, tzinfo=datetime.timezone.utc)),
        ),
    ]
